plugins {
  id("com.android.library")
  id("org.jetbrains.kotlin.android")
  id("expo-module-plugin")
}

def safeExtGet(String prop, int fallback) {
  return rootProject.hasProperty(prop) ? rootProject.ext.get(prop) as Integer : fallback
}

android {
  namespace = "com.allysonai.ttsdemo.phonemizer"
  compileSdkVersion safeExtGet("android.compileSdkVersion", 35)

  defaultConfig {
    minSdkVersion safeExtGet("android.minSdkVersion", 23)
    targetSdkVersion safeExtGet("android.targetSdkVersion", 35)
    consumerProguardFiles("consumer-rules.pro")
  }

  sourceSets {
    getByName("main") {
      java.srcDirs("src/main/kotlin")
      res.srcDirs("src/main/res")
    }
  }

  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
  }

  kotlinOptions {
    jvmTarget = "11"
  }
}

dependencies {
  implementation(project(":expo-modules-core"))
  implementation("androidx.core:core-ktx:1.13.1")
}
